name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        pip3 install wheel
        sudo apt-get install -y python3-setuptools
        pip3 install pylint
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Installed pylint now"
        pip3 show pylint
        EXPORT PATH=$PATH:/home/runner/.local/lib/python3.6/site-packages
        which pylint        
        pylint **/*.py
